api_version = "2025-04"

[[extensions]]
type = "ui_extension"
name = "Loyalty Credits - Customer Account"
handle = "loyalty-account"
uid = "8ea3c599-0904-df5e-db42-642a579c982e53dc2001"

[[extensions.targeting]]
target = "customer-account.profile.block.render"
module = "./src/ProfileBlock.jsx"

[[extensions.targeting]]
target = "customer-account.order-status.block.render"
module = "./src/OrderStatusBlock.jsx"

[[extensions]]
type = "ui_extension"
name = "Loyalty Credits - Rewards Page"
handle = "loyalty-rewards-page"
uid = "0fc6c198-fd63-a750-82f6-062482cea4a393aa6b8c"

[[extensions.targeting]]
target = "customer-account.page.render"
module = "./src/RewardsPage.jsx"
